//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UE4Assistant.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class ProjectTarget_cs : ProjectTarget_csBase {
        
        
        private string _targetnameField;

        public string targetname {
            get {
                return this._targetnameField;
            }
        }

        private string _targettypeField;

        public string targettype {
            get {
                return this._targettypeField;
            }
        }

        private System.Collections.Generic.List<System.String> _extramodulenamesField;

        public System.Collections.Generic.List<System.String> extramodulenames {
            get {
                return this._extramodulenamesField;
            }
        }

        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 10 ""
            this.Write("using UnrealBuildTool;\nusing System.Collections.Generic;\n\n\n\npublic class ");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.targetname ));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("Target : TargetRules\n{\n\tpublic ");
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.targetname ));
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write("Target(TargetInfo Target)\n\t\t: base(Target)\n\t{\n\t\tType = TargetType.");
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.targettype ));
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(@";
	}

	//
	// TargetRules interface.
	//

	public override void SetupBinaries(
		TargetInfo Target
		, ref List<UEBuildBinaryConfiguration> OutBuildBinaryConfigurations
		, ref List<string> OutExtraModuleNames
		)
	{
		OutExtraModuleNames.AddRange(new string[] { """);
            
            #line default
            #line hidden
            
            #line 33 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( System.String.Join("\",\"", this.extramodulenames) ));
            
            #line default
            #line hidden
            
            #line 33 ""
            this.Write("\" });\n\t}\n}\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                bool _targetnameAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("targetname"))) {
                    object data = this.Session["targetname"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._targetnameField = ((string)(data));
                        _targetnameAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'targetname\' did not match the type pas" +
                                "sed to the template");
                    }
                }
                if ((_targetnameAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("targetname");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._targetnameField = ((string)(data));
                            _targetnameAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'targetname\' did not match the type pas" +
                                    "sed to the template");
                        }
                    }
                }
                bool _targettypeAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("targettype"))) {
                    object data = this.Session["targettype"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._targettypeField = ((string)(data));
                        _targettypeAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'targettype\' did not match the type pas" +
                                "sed to the template");
                    }
                }
                if ((_targettypeAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("targettype");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._targettypeField = ((string)(data));
                            _targettypeAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'targettype\' did not match the type pas" +
                                    "sed to the template");
                        }
                    }
                }
                bool _extramodulenamesAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("extramodulenames"))) {
                    object data = this.Session["extramodulenames"];
                    if (typeof(System.Collections.Generic.List<System.String>).IsAssignableFrom(data.GetType())) {
                        this._extramodulenamesField = ((System.Collections.Generic.List<System.String>)(data));
                        _extramodulenamesAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.Collections.Generic.List<System.String>\' of the parameter \'extra" +
                                "modulenames\' did not match the type passed to the template");
                    }
                }
                if ((_extramodulenamesAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("extramodulenames");
                    if ((data != null)) {
                        if (typeof(System.Collections.Generic.List<System.String>).IsAssignableFrom(data.GetType())) {
                            this._extramodulenamesField = ((System.Collections.Generic.List<System.String>)(data));
                            _extramodulenamesAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.Collections.Generic.List<System.String>\' of the parameter \'extra" +
                                    "modulenames\' did not match the type passed to the template");
                        }
                    }
                }
            }

        }
    }
    
    public class ProjectTarget_csBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
